# Generated by Django 5.2 on 2025-05-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, choices=[('정치', '정치'), ('경제', '경제'), ('사회', '사회'), ('생활/문화', '생활/문화'), ('IT/기술', 'IT/기술')], max_length=20, null=True),
        ),
    ]
