# Generated by Django 5.2 on 2025-05-30 17:24

import easydigest.conf.asset_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=easydigest.conf.asset_storage.MediaStorage(), upload_to='profile_image/', verbose_name='프로필 이미지'),
        ),
    ]
