# Generated by Django 5.2 on 2025-04-30 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pos', models.CharField(max_length=30)),
                ('synonym', models.CharField(blank=True, max_length=200, null=True)),
                ('antonym', models.CharField(blank=True, max_length=200, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('ask_count', models.IntegerField(default=1)),
                ('correct_count', models.IntegerField(default=0)),
                ('last_learned', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
